Feature/plcn 66 commandhandler deal updated
it-minds/itm_pelican-crm-backend pull request #11
Opened 2022-10-28 08:25 UTC by Nicolai-Bak

2022-11-03 14:25 UTC, llh-itm commented on Pelican.Domain.Test/Entities/AccountManagerDealTests.cs
> +	public void Deactivate()
this test should probably have a more descriptive name

2022-11-03 14:25 UTC, llh-itm commented on Pelican.Presentation.Api/Controllers/HubSpotController.cs
>  					//"contact.propertyChange" => new UpdateContactCommand(propertyChangeRequest.ObjectId, propertyChangeRequest.PropertyName, propertyChangeRequest.PropertyValue),
is this commented out code no longer used? if so it should be deleted

2022-11-03 14:25 UTC, llh-itm commented on Pelican.Presentation.Api/Controllers/HubSpotController.cs
> +					"deal.propertyChange" => new UpdateDealCommand(request.ObjectId, request.PortalId, request.PropertyName, request.PropertyValue),
!-opreator on propertyName and propertyValue to remove warnings

2022-11-04 13:21 UTC, llh-itm approved these changes

2022-11-07 10:44 UTC, AntonEsbjergIT-Minds requested changes

2022-11-07 10:44 UTC, AntonEsbjergIT-Minds commented on Pelican.Domain.Test/Entities/DealTests.cs
> +	public void FillOutAccountmManager_AccountMaangerDealExists_OldAccountManagerDeactivated()
Spelling mistake, u decide if it is worth fixing

2022-11-07 10:44 UTC, AntonEsbjergIT-Minds commented on Pelican.Domain.Test/Entities/DealTests.cs
> +	public void FillOutAccountmManager_AccountMaangerDealExists_NewAccountManagerAdded()
Spelling mistake should me accountmanager instead of accountmaanger

2022-11-07 10:44 UTC, AntonEsbjergIT-Minds commented on Pelican.Domain.Test/Entities/DealTests.cs
> +	public void FillOutAccountmManager_SameAccountMaangerDealAlreadyExists_NewAccountManagerAdded()
Spelling mistake Accountmaanger should be accountmanager

2022-11-07 10:44 UTC, AntonEsbjergIT-Minds commented on Pelican.Domain/Entities/Deal.cs
> +	public Deal UpdateProperty(string propertyName, string propertyValue)
Is it bad practice to put all of this logic in the domain layer? It makes the updatehandler have a very rigid dependency on this class and makes it weird to test. I feel like there should be a better way, but perhaps that is a thing we should look into later.

2022-11-07 10:44 UTC, AntonEsbjergIT-Minds commented on Pelican.Domain/Entities/Deal.cs
> +			default:
If we are subscribed only to the relevant properties on hubspot somm kind of error must have happended for us to hit this code and we probably shoudl tell hubspot that.

2022-11-07 10:44 UTC, AntonEsbjergIT-Minds commented on Pelican.Domain/Entities/Deal.cs
> +		FillOutAccountmManager(accountManager);
Should be FillOutAccountManager

2022-11-07 10:44 UTC, AntonEsbjergIT-Minds commented on Pelican.Presentation.Api.Test/Controllers/HubSpotControllerTests.cs
> +		_senderMock.Verify(s => s.Send(It.IsAny<ICommand>(), _cancellationToken), Times.Once());
Should probably use the expected parameters in assert

2022-11-07 10:44 UTC, AntonEsbjergIT-Minds commented on Pelican.Presentation.Api.Test/Controllers/HubSpotControllerTests.cs
> +		_senderMock.Verify(s => s.Send(It.IsAny<UpdateDealCommand>(), _cancellationToken), Times.Once());
Should probably use the expected parameters in assert

2022-11-07 10:44 UTC, AntonEsbjergIT-Minds commented on Pelican.Presentation.Api/Controllers/HubSpotController.cs
> +	//[ServiceFilter(typeof(HubSpotValidationFilter))]
Why did you comment out the filter? Should it be removed?

2022-11-07 10:44 UTC, AntonEsbjergIT-Minds commented on Pelican.Presentation.Api/Controllers/HubSpotController.cs
> +					"deal.propertyChange" => new UpdateDealCommand(request.ObjectId, request.PortalId, request.PropertyName ?? string.Empty, request.PropertyValue ?? string.Empty),
Is string.Empty necesarry is the result not the same if they are there or not.

2022-11-07 13:23 UTC, Nicolai-Bak commented on Pelican.Application.Test/Deals/Commands/UpdateDeal/UpdateDealCommandHandlerTests.cs
> +				.FirstOrDefaultAsync(It.IsAny<Expression<Func<Supplier, bool>>>(), default),
Agree

2022-11-07 13:38 UTC, Nicolai-Bak commented on Pelican.Presentation.Api/Controllers/HubSpotController.cs
> +	//[ServiceFilter(typeof(HubSpotValidationFilter))]
uncommented

2022-11-08 09:45 UTC, Nicolai-Bak commented on Pelican.Domain/Entities/Deal.cs
> +	public Deal UpdateProperty(string propertyName, string propertyValue)
As I know its not bad practice to put logic without external dependencies into the domain models. At the same time I agree that in makes the dependency from handler to model stronger. For now public methods in Deal is made virtual which makes it possible to mock them in unit tests. By this the classes can be tested individually.

2022-11-08 13:23 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Deals/Commands/UpdateDeal/UpdateDealCommandHandlerTests.cs
> +	public async void Handle_DealNotFoundFailsRefreshingToken_ReturnsFailure()
Fair enough

2022-11-08 13:36 UTC, AntonEsbjergIT-Minds commented on Pelican.Application/Deals/Commands/UpdateDeal/UpdateDealCommandHandler.cs
> +		Deal deal = await FillOutDealAssociations(result.Value, cancellationToken);
Looks good, I like the change

2022-11-08 13:41 UTC, AntonEsbjergIT-Minds commented on Pelican.Domain/Entities/Deal.cs
> +	public Deal UpdateProperty(string propertyName, string propertyValue)
Sounds good

2022-11-08 13:42 UTC, AntonEsbjergIT-Minds approved these changes

2022-11-08 13:45 UTC, merged