Feature/plcn 378 create update user command validator
it-minds/itm_pelican-crm-backend pull request #114
Opened 2022-12-30 07:56 UTC by Nicolai-Bak

Validator for UpdateUserCommand added

2023-01-03 08:48 UTC, itm-mne approved these changes

2023-01-03 12:45 UTC, AntonEsbjergIT-Minds requested changes

2023-01-03 12:45 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandValidator.cs
> +			.MaximumLength(StringLengths.Email);
This check seems unnecessary since we shorten any Email that is too long, though perhaps this should be used instead of that shortening.

2023-01-03 12:45 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandValidator.cs
> +			.MaximumLength(StringLengths.Name);
This check seems unnecessary since we shorten any Name that is too long, though perhaps this should be used instead of that shortening.

2023-01-03 12:45 UTC, AntonEsbjergIT-Minds commented on test/Pelican.Application.Test/Users/Commands/UpdateUser/UpdateUserCommandValidatorTests.cs
> +public class UpdateUserCommandValidatorTests
I think you also need tests to check for email that an error happens if it it is too long or if it is in incorrect format. I also think you should make a test for if name is too long.

2023-01-04 10:48 UTC, Nicolai-Bak commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandValidator.cs
> +			.MaximumLength(StringLengths.Email);
As the user becomes invalid if we just shorten the property i think this would be a better approach.
Should we remove the shortening from the entity?

2023-01-04 10:48 UTC, Nicolai-Bak commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandValidator.cs
> +			.MaximumLength(StringLengths.Name);
As the user becomes invalid if we just shorten the property i think this would be a better approach.
Should we remove the shortening from the entity?

2023-01-04 10:48 UTC, Nicolai-Bak commented on test/Pelican.Application.Test/Users/Commands/UpdateUser/UpdateUserCommandValidatorTests.cs
> +public class UpdateUserCommandValidatorTests
If we decide to keep the validation I will add tests

2023-01-04 13:13 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandValidator.cs
> +			.MaximumLength(StringLengths.Email);
Should we make a branch where we do it for all entities?

2023-01-04 13:59 UTC, Nicolai-Bak commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandValidator.cs
> +			.MaximumLength(StringLengths.Email);
Now it is removed only for the User Entity as we talked about

2023-01-05 09:29 UTC, AntonEsbjergIT-Minds approved these changes

2023-01-05 10:01 UTC, merged