Feature/plcn 370 create reset password command
it-minds/itm_pelican-crm-backend pull request #117
Opened 2023-01-02 08:29 UTC by AntonEsbjergIT-Minds

2023-01-02 14:33 UTC, itm-mne approved these changes

2023-01-03 08:36 UTC, Nicolai-Bak approved these changes

2023-01-03 09:32 UTC, merged

2023-01-03 09:33 UTC, Nicolai-Bak requested changes

2023-01-03 09:33 UTC, Nicolai-Bak commented on src/Pelican.Application/Authentication/ResetPassword/ResetPasswordCommand.cs
> +namespace Pelican.Application.Authentication.ResetPassword;
Would prefer having this under Pelican.Application/Users/Commands