Feature/plcn 373 create update password command handler
it-minds/itm_pelican-crm-backend pull request #125
Opened 2023-01-04 14:50 UTC by Nicolai-Bak

Added handler to update a users password. Returns error if user is not found. If found password will be updated

2023-01-04 14:55 UTC, simonitminds commented
all checks failed

2023-01-04 14:55 UTC, simonitminds commented
![image](https://user-images.githubusercontent.com/56028412/210582673-abc52fdf-84ed-420e-9311-692216737898.png)

2023-01-04 15:04 UTC, Nicolai-Bak commented
> ![image](https://user-images.githubusercontent.com/56028412/210582673-abc52fdf-84ed-420e-9311-692216737898.png)

![image](https://user-images.githubusercontent.com/79926921/210584691-599aacfd-c7c4-4661-82b1-fe07544fcdce.png)

2023-01-04 15:22 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Users/Commands/UpdatePassword/UpdatePasswordCommandHandler.cs
> +		_passwordHasher = passwordHasher;
Since we have done it in many commandhandlers should we check if the parameters given in the constructor are null and cast an exception if they are?

2023-01-05 08:08 UTC, s-bogelund approved these changes

2023-01-05 12:10 UTC, AntonEsbjergIT-Minds requested changes

2023-01-05 12:10 UTC, AntonEsbjergIT-Minds commented on test/Pelican.Application.Test/Users/Commands/UpdatePassword/UpdatePasswordCommandHandlerTests.cs
> +		Assert.True(result.IsSuccess);
I think you should verify that update and save is called

2023-01-05 12:10 UTC, AntonEsbjergIT-Minds commented on test/Pelican.Application.Test/Users/Commands/UpdatePassword/UpdatePasswordCommandHandlerTests.cs
> +		Assert.True(result.IsFailure);
Verify the call to UserRepo

2023-01-06 08:10 UTC, AntonEsbjergIT-Minds approved these changes

2023-01-06 08:22 UTC, merged