Feature/plcn 360 create update user command handler
it-minds/itm_pelican-crm-backend pull request #130
Opened 2023-01-05 14:48 UTC by Nicolai-Bak

Added handler to update email and name on user entity. Fails if user not found or if email is already used by another user.

2023-01-06 08:34 UTC, AntonEsbjergIT-Minds requested changes

2023-01-06 08:34 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +				expression: u => u.Id == command.User.Id,
Named argument specifications seem unnecessary

2023-01-06 08:34 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +				message: $"{command.User.Id} was not found");
This message doesn't seems that useful. You are returning "{guid} was not found" Perhaps change it to sayre "User with id: {Guid} was not found" or "Id for user {user.Name} was not found"

2023-01-06 08:34 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +		user.Name = command.User.Name ?? user.Name;
You lack a test for the branch where command.User.Name is null

2023-01-06 08:34 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +		user.Email = command.User.Email ?? user.Email;
You lack a test for the branch where command.User.Email is null

2023-01-06 08:34 UTC, AntonEsbjergIT-Minds commented on test/Pelican.Application.Test/Users/Commands/UpdateUser/UpdateUserCommandHandlerTests.cs
> +	public async void Handle_UserUpdated_ReturnFailure()
Name should be Handle_UserUpdated_ReturnsSuccess()

2023-01-06 08:34 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +		if (command.User.Email is not null && await _unitOfWork
Add a test where Email is null

2023-01-06 13:57 UTC, Nicolai-Bak commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +		user.Email = command.User.Email ?? user.Email;
branch removed

2023-01-06 13:57 UTC, Nicolai-Bak commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +		user.Name = command.User.Name ?? user.Name;
branch removed

2023-01-06 13:58 UTC, Nicolai-Bak commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +				expression: u => u.Id == command.User.Id,
removed

2023-01-06 14:02 UTC, Nicolai-Bak commented on src/Pelican.Application/Users/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +		if (command.User.Email is not null && await _unitOfWork
branch removed as validator does not allow email to be null

2023-01-09 09:33 UTC, AntonEsbjergIT-Minds approved these changes

2023-01-09 10:07 UTC, itm-mne approved these changes

2023-01-09 10:16 UTC, merged