Feature/plcn 351 create check auth command handler
it-minds/itm_pelican-crm-backend pull request #131
Opened 2023-01-06 08:37 UTC by Nicolai-Bak

Added handler to check if current user is valid 

Added implicit operator to Result type to avoid explicit cast from error to result

2023-01-06 08:57 UTC, AntonEsbjergIT-Minds requested changes

2023-01-06 08:57 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Authentication/CheckAuth/CheckAuthCommandHandler.cs
> +			Role = user.Role,
I think you will find that this role assigment always sets the role to 0.

2023-01-06 08:57 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Authentication/CheckAuth/CheckAuthCommandHandler.cs
> +			Role = user.Role,
You need to use automapper to fix this. I have added automapper in one of my PR's https://itminds.atlassian.net/browse/PLCN-371. When it is merged I think you should rebase this branch in use Automapper to map the returned user to an UserDto.

2023-01-06 08:57 UTC, AntonEsbjergIT-Minds commented on test/Pelican.Application.Test/Authentication/CheckAuth/CheckAuthCommandHandlerTests.cs
> +	public async void Handle_UserFound_ReturnsSuccess()
I think you should assign values to user found and check that the result.Value has the same values as the returned user.

2023-01-09 09:30 UTC, AntonEsbjergIT-Minds approved these changes

2023-01-09 10:09 UTC, itm-mne approved these changes

2023-01-09 10:17 UTC, merged