Create README.md
it-minds/itm_pelican-crm-backend pull request #149
Opened 2023-01-19 12:39 UTC by AntonEsbjergIT-Minds

Signed-off-by: AntonEsbjergIT-Minds <112855152+AntonEsbjergIT-Minds@users.noreply.github.com>

2023-01-19 12:46 UTC, itm-mne approved these changes

2023-01-19 13:24 UTC, Nicolai-Bak requested changes
Missing information about the need of setting local secret before running the application

2023-01-19 13:24 UTC, Nicolai-Bak commented on README.md
> +  - **Pelican.*.Tests** - Contains tests for the given project.
Tests is not in src folder

2023-01-20 08:11 UTC, Nicolai-Bak approved these changes

2023-01-20 08:12 UTC, merged