Feature/plcn 159 add startup project
it-minds/itm_pelican-crm-backend pull request #15
Opened 2022-11-03 13:05 UTC by Nicolai-Bak

2022-11-04 07:41 UTC, Nicolai-Bak commented on Pelican.App/Program.cs
> +app.UseApi();
The Pelican.App project is added In an attempt to follow the principles of Clean Architecture. 
By adding the new project as the startup project it is possible to remove infrastructure dependencies from the presentation layer as it was only used to add services and middleware.
In addition, it removes the doubt as to which Presentation project the program file belongs

2022-11-04 08:27 UTC, Nicolai-Bak commented on Pelican.Domain/Settings/HubSpotAppSettings.cs
> +﻿namespace Pelican.Domain.Settings;
Both presentation.api and infrastructure.hubspot needs access to the settings and as they do not depend on each other anymore the settings was moved

2022-11-04 11:00 UTC, AntonEsbjergIT-Minds requested changes
I have created the first two changes myself but. the last one about renaming you could do if you think it should be

2022-11-04 13:03 UTC, Nicolai-Bak commented on Pelican.Architecture.Test/ProjectReferencesTests.cs
> +	public void Domain_ShouldNotDependOn()
"_IsSuccessful" added

2022-11-04 13:04 UTC, Nicolai-Bak commented on Pelican.Architecture.Test/ProjectReferencesTests.cs
> +	private const string DOMAIN_NAMESPACE = "Pelican.Domain";
removed

2022-11-07 08:54 UTC, llh-itm commented on Pelican.App/Program.cs
> +app.UseApi();
that makes sense, in that case this seems like a good solution then:)

2022-11-07 08:54 UTC, llh-itm commented on Pelican.Application/Pelican.Application.csproj
>  		<PackageReference Include="MediatR" Version="11.0.0" />
is mediatR used in this project?

2022-11-07 08:54 UTC, llh-itm commented on Pelican.Infrastructure.HubSpot/Pelican.Infrastructure.HubSpot.csproj
>  		<PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
looks like Microsoft.Extensions.Http can be removed as well

2022-11-07 08:55 UTC, llh-itm commented on Pelican.Domain/Settings/HubSpotAppSettings.cs
> +﻿namespace Pelican.Domain.Settings;
that makes sense, in that case this seems like a good solution then:)

2022-11-07 08:55 UTC, llh-itm commented on Pelican.App/Program.cs
> +app.UseApi();
that makes sense, in that case this seems like a good solution then:)

2022-11-07 10:41 UTC, Nicolai-Bak commented on Pelican.Application/Pelican.Application.csproj
>  		<PackageReference Include="MediatR" Version="11.0.0" />
MediatR is used to implement Query- and CommandHandlers

2022-11-07 10:47 UTC, Nicolai-Bak commented on Pelican.Infrastructure.HubSpot/Pelican.Infrastructure.HubSpot.csproj
>  		<PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
true, removed now

2022-11-07 10:55 UTC, llh-itm commented on Pelican.Application/Pelican.Application.csproj
>  		<PackageReference Include="MediatR" Version="11.0.0" />
ahh i see

2022-11-07 10:56 UTC, llh-itm approved these changes

2022-11-07 12:10 UTC, merged