Feature/plcn 67 command and handler for client entity
it-minds/itm_pelican-crm-backend pull request #17
Opened 2022-11-04 10:25 UTC by AntonEsbjergIT-Minds

2022-11-07 10:39 UTC, Nicolai-Bak requested changes

2022-11-07 10:39 UTC, Nicolai-Bak commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +		Assert.Empty(Client.ClientContacts);
If the hubspotclient has clientcontacts, why should this be empty?

2022-11-07 10:39 UTC, Nicolai-Bak commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +		_unitOfWorkMock.Verify(x => x.ClientRepository.Update(client));
add `, Times.Once()` on all verify update

2022-11-07 10:39 UTC, Nicolai-Bak commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +	public async void Handle_ClientFoundNumAssociatedContactUpdatedButClientContactsInClientNotTheSameAsInHubSpotClient_ReturnsSuccess(
This and next should not be necessary as hubspot clientid in client and clientHubspot should be the same when both is fetched by id

2022-11-07 10:39 UTC, Nicolai-Bak commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +		UpdateClientCommand command = new(objectId, portalId, propertyName, propertyValue);
Add '// Assert' to tests where it is missing

2022-11-07 12:24 UTC, AntonEsbjergIT-Minds commented on Pelican.Presentation.Api/Controllers/HubSpotController.cs
> +	//[ServiceFilter(typeof(HubSpotValidationFilter))]
Removed Comment

2022-11-07 12:25 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandValidatorUnitTest.cs
> +	public void UpdateClientCommandCommandValidator_EmptyOrDefaultInputs_ReturnsError()
Whoops, name has been changed

2022-11-07 12:29 UTC, AntonEsbjergIT-Minds commented on Pelican.Application/Clients/Commands/DeleteClient/DeleteClientCommandHandler.cs
> +		_unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(IUnitOfWork));
Changed it to be nameof parameter

2022-11-07 12:30 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/DeleteClient/DeleteClientCommandValidatorUnitTest.cs
> +	public void DeleteClientCommandCommandValidator_EmptyId_ReturnsError()
Whoops, implemented the change

2022-11-07 12:31 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/DeleteClient/DeleteClientCommandValidatorUnitTest.cs
> +		DeleteClientCommand command = new(long.MinValue);
Moved, into one test theory with inline data.

2022-11-07 12:34 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/DeleteClient/DeleteClientCommandHandlerUnitTest.cs
> +	private CancellationToken cancellation;
Added '_' prefix and also made readonly

2022-11-07 12:38 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/DeleteClient/DeleteClientCommandHandlerUnitTest.cs
> +			.FindByCondition(It.IsAny<System.Linq.Expressions.Expression<Func<Client, bool>>>()))
Yes. added it and shortened test names.

2022-11-08 07:38 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/DeleteClient/DeleteClientCommandHandlerUnitTest.cs
> +			Times.Once());
Added

2022-11-08 07:44 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/DeleteClient/DeleteClientCommandHandlerUnitTest.cs
> +		fakeUnitOfWork.Verify(x => x.SaveAsync(cancellation), Times.Never());
Rearranged so saveasync is last

2022-11-08 07:55 UTC, AntonEsbjergIT-Minds commented on Pelican.Application/Clients/Commands/UpdateClient/UpdateClientCommandHandler.cs
> +		if (supplier is null || supplier.RefreshToken is null || supplier.RefreshToken == "")
Done :D

2022-11-08 07:55 UTC, AntonEsbjergIT-Minds commented on Pelican.Application/Clients/Commands/UpdateClient/UpdateClientCommandHandler.cs
> +		if (supplier is null || supplier.RefreshToken is null || supplier.RefreshToken == "")
Done :D

2022-11-08 08:40 UTC, AntonEsbjergIT-Minds commented on Pelican.Application/Clients/Commands/UpdateClient/UpdateClientCommandHandler.cs
> +			.RefreshAccessTokenAsync(supplier.RefreshToken, cancellationToken);
Created a new method to get access token

2022-11-08 08:40 UTC, AntonEsbjergIT-Minds commented on Pelican.Application/Clients/Commands/UpdateClient/UpdateClientCommandHandler.cs
> +					.Update(localClient);
Done

2022-11-08 08:48 UTC, AntonEsbjergIT-Minds commented on Pelican.Application/Clients/Commands/UpdateClient/UpdateClientCommandHandler.cs
> +			}
Added a new foreach loop that adds any client contacts in result which aren't in local to local

2022-11-08 09:27 UTC, AntonEsbjergIT-Minds commented on Pelican.Application/Clients/Commands/UpdateClient/UpdateClientCommandHandler.cs
> +		Result<Client> result = await _hubSpotClientService.GetByIdAsync(accessTokenResult.Value, objectId, cancellationToken);
Now adds a contact with contactid.

2022-11-08 09:29 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +	private readonly Mock<IGenericRepository<Client>> _ClientRepositoryMock;
Changed the name

2022-11-08 09:50 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +				Times.Once());
Tried to fix indentation

2022-11-08 09:51 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +				.FindByCondition(It.IsAny<System.Linq.Expressions.Expression<Func<Client, bool>>>()))
Done

2022-11-08 09:51 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +		_unitOfWorkMock.Verify(x => x.SupplierRepository.FindByCondition(s => s.HubSpotId == portalId));
I concluded that, it was a bit superflous, I just checked it the first time.

2022-11-08 09:55 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +		// Assert
Added Verify on Createasync()

2022-11-08 09:59 UTC, AntonEsbjergIT-Minds commented on Pelican.Application/Clients/Commands/UpdateClient/UpdateClientCommandHandler.cs
> +			default:
Added exception

2022-11-08 10:03 UTC, AntonEsbjergIT-Minds commented on Pelican.Application/Clients/Commands/UpdateClient/UpdateClientCommandHandler.cs
> +			default:
And a test for this scenario

2022-11-08 10:13 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +		Client Client = new(Guid.NewGuid());
Changed

2022-11-08 10:26 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +		updatedClient.Name = command.PropertyValue;
Changed it to Assert.Equal(command.PropertyValue, client.RelevanctProperty)

Relevant Property is in this case .Name

2022-11-08 10:29 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +		UpdateClientCommand command = new(objectId, portalId, propertyName, propertyValue);
Added //Arrange to test where it was missing

2022-11-08 10:41 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +		Assert.Empty(Client.ClientContacts);
With the changes you suggested earlier you are right, I have changed the test now.

2022-11-08 10:41 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +	public async void Handle_ClientFoundNumAssociatedContactUpdatedButClientContactsInClientNotTheSameAsInHubSpotClient_ReturnsSuccess(
Removed

2022-11-08 10:42 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +		_unitOfWorkMock.Verify(x => x.ClientRepository.Update(client));
Whoops, have been added

2022-11-08 14:21 UTC, llh-itm commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +	private void SetupUnitOfWork()
this method is only called in the test below it but is immediately overwritten in the test anyway - should be removed

2022-11-08 14:21 UTC, llh-itm commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +		SetupUnitOfWork();
does nothing, remove

2022-11-09 07:58 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +	private void SetupUnitOfWork()
Has been removed

2022-11-09 07:58 UTC, AntonEsbjergIT-Minds commented on Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientCommandHandlerUnitTest.cs
> +		SetupUnitOfWork();
Removed

2022-11-10 10:06 UTC, Nicolai-Bak approved these changes

2022-11-10 10:38 UTC, merged