secrets removed from appsettings
it-minds/itm_pelican-crm-backend pull request #19
Opened 2022-11-08 12:38 UTC by Nicolai-Bak

Secret settings removed from appsettings to use user-secrets and azure key-vault on deployment

2022-11-08 13:44 UTC, llh-itm requested changes

2022-11-08 13:44 UTC, llh-itm commented on Pelican.App/appsettings.json
> -			"ClientSecret": "1dfc68f9-9ed7-41c8-a45a-ffc32bf274d8"
this secret should probably be removed completely from the git history as well - its usually never a good thing to have secrets stored in the repo

2022-11-09 08:03 UTC, AntonEsbjergIT-Minds approved these changes

2022-11-10 09:31 UTC, s-bogelund approved these changes

2022-11-15 13:44 UTC, Nicolai-Bak commented on Pelican.App/appsettings.json
> -			"ClientSecret": "1dfc68f9-9ed7-41c8-a45a-ffc32bf274d8"
This hubspot app is only accesses for individual local testing and will never access real data.
Hubspot secrets for demo and production will only be stored on Azure

2022-11-16 07:45 UTC, AntonEsbjergIT-Minds approved these changes

2022-11-16 08:36 UTC, llh-itm commented on Pelican.App/appsettings.json
> -			"ClientSecret": "1dfc68f9-9ed7-41c8-a45a-ffc32bf274d8"
i see - in generel secrets should never be saved in the repo, but if its only used for local testing its not super important

2022-11-16 08:37 UTC, llh-itm approved these changes

2022-11-16 09:08 UTC, merged