Feature/plcn 267 move reusable code from hubspot to application
it-minds/itm_pelican-crm-backend pull request #62
Opened 2022-12-02 08:53 UTC by Nicolai-Bak

2022-12-02 12:17 UTC, AntonEsbjergIT-Minds requested changes

2022-12-02 12:17 UTC, AntonEsbjergIT-Minds commented on test/Pelican.Infrastructure.HubSpot.Test/Services/HubSpotClientServicesTests.cs
> +	public void HubSpotClientService_ClientNull_ThrowException()
This test should also be added to HubSpotAccountManagerServicesTests

2022-12-02 12:17 UTC, AntonEsbjergIT-Minds commented on test/Pelican.Infrastructure.HubSpot.Test/Services/HubSpotContactServicesTests.cs
>  		_uut = new HubSpotContactService(_hubSpotClientMock.Object);
Maybe also add test to see what happens if a null value is given as hubSpotClient

2022-12-02 12:17 UTC, AntonEsbjergIT-Minds commented on test/Pelican.Infrastructure.HubSpot.Test/Services/HubSpotDealServicesTests.cs
>  		_uut = new HubSpotDealService(_hubSpotClientMock.Object);
Maybe add a test for what happens if null is given as Hubspotclient

2022-12-05 15:16 UTC, Nicolai-Bak commented on src/Pelican.Domain/Settings/HubSpotSettings.cs
> +public sealed class HubSpotSettings : BaseSettings
Made base class to abstract RestSharp implementation. 
Now RestSharp implementation can be used with or without baseurl with the same implementation

2022-12-06 08:56 UTC, AntonEsbjergIT-Minds approved these changes

2022-12-06 08:56 UTC, merged