Feature/plcn 227 retry handling on web hooks
it-minds/itm_pelican-crm-backend pull request #70
Opened 2022-12-08 08:12 UTC by AntonEsbjergIT-Minds

2022-12-12 08:03 UTC, itm-mne commented on src/Pelican.Domain/Entities/AccountManager.cs
> +	public long? SourceUpdateTimestamp { get; set; }
Would you like a comment here to make you aware of the above warnings, or are you already handling this warning?

2022-12-12 12:25 UTC, Nicolai-Bak requested changes

2022-12-12 12:25 UTC, Nicolai-Bak commented on src/Pelican.Application/Contacts/HubSpotCommands/Update/UpdateContactHubSpotCommandHandler.cs
> +				.Update(contact);
And correct indentation on line 112,113,114 and 132,133,134

2022-12-12 12:25 UTC, Nicolai-Bak commented on src/Pelican.Application/Clients/HubSpotCommands/Update/UpdateClientHubSpotCommandHandler.cs
> +		if (client.SourceUpdateTimestamp <= command.UpdateTime && client.CreatedAt <= command.UpdateTime)
Is check on CreatedAt necessary or should we just always set SourceUpdateTimestamp when creating a new instance? 
Question applies for contacts and deals as well

2022-12-12 12:25 UTC, Nicolai-Bak commented on src/Pelican.Application/Clients/HubSpotCommands/Update/UpdateClientHubSpotCommandHandler.cs
>  						cancellationToken);
indentation, on line 124,125,126 too

2022-12-12 12:25 UTC, Nicolai-Bak commented on src/Pelican.Application/Clients/HubSpotCommands/Update/UpdateClientHubSpotCommandHandler.cs
> -
Generally i would prefer kepping the line spacing between different method calls for readability

2022-12-12 12:25 UTC, Nicolai-Bak commented on test/Pelican.Domain.Test/Entities/ContactTests.cs
> +		long updatetime = 1;
never used

2022-12-12 12:25 UTC, Nicolai-Bak commented on test/Pelican.Domain.Test/Entities/DealTests.cs
> +
redundant line

2022-12-12 12:25 UTC, Nicolai-Bak commented on test/Pelican.Domain.Test/Entities/ContactTests.cs
> +		Mock<Contact> contactMock = new();
What is the idea behind using a mock for this?

2022-12-13 08:03 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Domain/Entities/AccountManager.cs
> +	public long? SourceUpdateTimestamp { get; set; }
Supplier is now nullable which removes the warning :)

2022-12-13 08:05 UTC, AntonEsbjergIT-Minds commented on test/Pelican.Domain.Test/Entities/ClientUnitTest.cs
> +		long updateTime = 1;
Has been removed

2022-12-13 08:22 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Infrastructure.Persistence/Migrations/20221208085708_SourceUpdateTime.cs
> +                nullable: true);
Removed the migration and added a new one where all Entities have a nullable SourceUpdateTime.

2022-12-13 08:25 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Infrastructure.HubSpot/Contracts/Responses/Clients/CompanyProperties.cs
> +	public long ChangedUnixTime { get; set; }
Has now been moved there :)

2022-12-13 08:27 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Infrastructure.HubSpot/Contracts/Responses/Deals/DealProperties.cs
> +	public long ChangedUnixTime { get; set; }
Now inherits from HubSpotObjectProperties

2022-12-13 08:29 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Contacts/HubSpotCommands/Update/UpdateContactHubSpotCommandHandler.cs
> +				.Update(contact);
Done

2022-12-13 08:29 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Contacts/HubSpotCommands/Update/UpdateContactHubSpotCommandHandler.cs
>  			}
Done

2022-12-13 09:09 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Clients/HubSpotCommands/Update/UpdateClientHubSpotCommandHandler.cs
> +		if (client.SourceUpdateTimestamp <= command.UpdateTime && client.CreatedAt <= command.UpdateTime)
Now since we removed SourceUpdateTimeStamp I think we need to check on both.

2022-12-13 09:13 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Application/Clients/HubSpotCommands/Update/UpdateClientHubSpotCommandHandler.cs
> -
Fixed it in this file and will keep in mind in the future

2022-12-13 09:14 UTC, AntonEsbjergIT-Minds commented on test/Pelican.Domain.Test/Entities/ContactTests.cs
> +		long updatetime = 1;
removed

2022-12-14 09:55 UTC, Nicolai-Bak approved these changes

2022-12-14 09:55 UTC, merged