Attempt to make ClientContact update correctly
it-minds/itm_pelican-crm-backend pull request #71
Opened 2022-12-09 10:36 UTC by AntonEsbjergIT-Minds

2022-12-12 10:27 UTC, Nicolai-Bak commented on src/Pelican.Domain/Entities/Client.cs
> -			&& currentClientContact.Contact.Source == clientContact.Contact.Source))
Why is source check removed?

2022-12-12 10:27 UTC, Nicolai-Bak commented on src/Pelican.Application/Clients/HubSpotCommands/UpdateClient/UpdateClientHubSpotCommandHandler.cs
> +				.FirstOrDefault();
For deals i moved this of contacting the database to the mapping part of Infrastructure.HubSpot.  I think we should either do the same for client or I should revert my changes to keep the same structure for hubspot handlers?

2022-12-12 10:46 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Domain/Entities/Client.cs
> -			&& currentClientContact.Contact.Source == clientContact.Contact.Source))
That check seemed superflous, since when we gotten the currentclientcontact we checked that the clients source was HubSpot and the other ClientContacts was gotten from fetching the client from HubSpot. But I added a source check like this back: 
&& currentClientContact.Client.Source == clientContact.Client.Source

2022-12-16 09:23 UTC, Nicolai-Bak requested changes

2022-12-16 09:23 UTC, Nicolai-Bak commented on test/Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientHubSpotCommandHandlerUnitTest.cs
> +			.ReturnsAsync(Result.Success("AccessToken"));
accessToken on line 610 is not used now

2022-12-16 09:25 UTC, itm-mne approved these changes
No comment since last review

2022-12-16 09:36 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Infrastructure.HubSpot/Mapping/Clients/CompanyResponseToClient.cs
>  		return result;
Done

2022-12-16 09:36 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Infrastructure.HubSpot/Mapping/Clients/CompanyResponseToClient.cs
> +			.Select(t => t.Result).ToList());
Moved

2022-12-16 09:36 UTC, AntonEsbjergIT-Minds commented on src/Pelican.Infrastructure.HubSpot/Mapping/Clients/CompanyResponseToClient.cs
> +			.Select(t => t.Result).ToList());
Moved

2022-12-16 09:41 UTC, AntonEsbjergIT-Minds commented on test/Pelican.Application.Test/Clients/Commands/UpdateClient/UpdateClientHubSpotCommandHandlerUnitTest.cs
> +			.ReturnsAsync(Result.Success("AccessToken"));
Fixed

2022-12-19 08:16 UTC, Nicolai-Bak requested changes

2022-12-19 08:16 UTC, Nicolai-Bak commented on src/Pelican.Application/Clients/HubSpotCommands/Update/UpdateClientHubSpotCommandHandler.cs
>  		if (client is null)
line 36 and 37 is switched

2022-12-19 08:33 UTC, Nicolai-Bak approved these changes

2022-12-19 08:33 UTC, merged