Feature/plcn 299 remove entity constructors with guid
it-minds/itm_pelican-crm-backend pull request #84
Opened 2022-12-19 09:33 UTC by Nicolai-Bak

Constructors with id parameter is only used in tests and should not be used in source code therefore the constructor is removed. 

All changes should only be removing the id when instantiating an object so it should be pretty easy to review even though lots of files is changed.

2022-12-19 09:42 UTC, AntonEsbjergIT-Minds reviewed
I was thinking could you supress the warnings due to nonullable values not having a value when exiting constructor on all Entities?

2022-12-19 10:03 UTC, AntonEsbjergIT-Minds requested changes
You should also remove the rule in PelicanBogusFaker whichsets entity ID to a randome new Guid :D

2022-12-19 10:40 UTC, AntonEsbjergIT-Minds approved these changes

2022-12-20 08:58 UTC, s-bogelund approved these changes

2022-12-20 12:16 UTC, merged